### ISSUE TITLE
Error handeling on invalid input - geopackage writer as example

### ISSUE THREAD

**Issue by MFuglsang** [MFuglsang/QGIS_ETL_Python#20]
The _typo writer.geopackage(reprojectedlayer,'Busstops','c:/temp/fynbus.gpkg',**true**)_ does not yield the correct error handeling - nothing is written to the log file, and the script terminates the wrong way...

**Comment by MFuglsang** [comment]
Errors that stems from the users own python code is not handled as an exception that gets logged...

**Comment by MFuglsang** [comment]
I think we fixed this one by adding stdout to the logfile

**Comment by danielarnason** [comment]
Just tested it. Stdout is printed in the terminal and logfile.
![image](https://github.com/user-attachments/assets/77c45953-1d2d-410e-80a0-a536cd327f9c)
