### ISSUE TITLE
writeAsVectorFormat deprecated

### ISSUE THREAD

**Issue by danielarnason** [MFuglsang/QGIS_ETL_Python#9]
The `writeAsVectorFormat` method is deprecated ([writeAsVectorFormat docs](https://qgis.org/pyqgis/master/core/QgsVectorFileWriter.html#qgis.core.QgsVectorFileWriter.writeAsVectorFormat)). 
We should probably use the `writeAsVectorFormatV3` method instead ([writeAsVectorFormatV3 docs](https://qgis.org/pyqgis/master/core/QgsVectorFileWriter.html#qgis.core.QgsVectorFileWriter.writeAsVectorFormatV3)).

**Comment by MFuglsang** [comment]
There is issues making this migration in headless mode. It requires something of qgis, that I haven't been able to figure out what is exactly.

**Comment by MFuglsang** [comment]
This should be fixable @danielarnason  - we have one writer doing it right I think ?
